# Seminar 7.2 - **Seaborn**  

## Introduksjon  
I dette seminaret skal vi jobbe med visualisering av data ved hjelp av **Seaborn**, som er et Python-bibliotek bygget på toppen av Matplotlib. Seaborn gjør det enkelt å lage flotte og informative visualiseringer, og det er spesielt nyttig når vi arbeider med store datasett.

I de forrige seminarene har vi arbeidet med:  
- **Variabler og funksjoner**  
- **Lister og datastrukturer**  
- **NumPy** (numeriske beregninger)  
- **Pandas** (databehandling)  
- **matplotlib**

Visualisering av data er viktig for å kunne forstå mønstre og kommunisere funn på en effektiv måte. Som samfunnsøkonomer og økonomer bruker vi ofte visualiseringer for å forklare og analysere data, og Seaborn er et utmerket verktøy for dette.

## Hvorfor *Seaborn*?  
[Seaborn](https://seaborn.pydata.org/) er et bibliotek som forenkler prosessen med å lage visualiseringer som linjediagrammer, histogrammer, korrelasjonsmatriser, boksplotter, og mye mer. Seaborn har flere fordeler:  
- Lett å bruke med Pandas DataFrames  
- Har innebygde temaer og farger for vakre visualiseringer  
- Støtter statistisk visualisering, som regressjonslinjer og distribusjonsplotter  
- Gir enklere tilgang til komplekse plott som for eksempel varmekart og pairplots  

I dette seminaret skal vi bruke Seaborn for å visualisere data og trekke innsikt fra grafene.

## Seminaroppgaver  
Disse oppgavene er laget for å gi deg trening i å lage visualiseringer og analysere data ved hjelp av Seaborn. **Dette er ikke arbeidskrav**, men det vil gi deg en god forberedelse til eksamen.  

Bruk **Google, forelesningsnotater og pseudokode** aktivt for å løse oppgavene.

🚀 *Lykke til!*

# Datasett for seminar
I forbindelse med denne oppgaven henter vi et datasett fra Kaggle. Les mer om datasettet [her](https://www.kaggle.com/datasets/lainguyn123/student-performance-factors).

Dette datasettet gir en omfattende oversikt over ulike faktorer som påvirker studenters prestasjoner på eksamener. Det inkluderer informasjon om studievaner, oppmøte, foreldreinvolvering og andre aspekter som har innflytelse på akademisk suksess.

Kolonnene i datasettet er:
| **Attributt**                  | **Beskrivelse**                                                              |
|---------------------------------|------------------------------------------------------------------------------|
| Hours_Studied                  | Antall timer brukt på å studere per uke.                                      |
| Attendance                     | Prosentandel av klasser eleven har deltatt i.                                 |
| Parental_Involvement            | Nivå av foreldreinvolvering i elevens utdanning (Lav, Middels, Høy).          |
| Access_to_Resources             | Tilgang til utdanningsressurser (Lav, Middels, Høy).                          |
| Extracurricular_Activities      | Deltakelse i fritidsaktiviteter (Ja, Nei).                                    |
| Sleep_Hours                     | Gjennomsnittlig antall timer søvn per natt.                                   |
| Previous_Scores                 | Karakterer fra tidligere eksamener.                                           |
| Motivation_Level                | Elevens motivasjonsnivå (Lav, Middels, Høy).                                  |
| Internet_Access                 | Tilgang til internett (Ja, Nei).                                              |
| Tutoring_Sessions               | Antall veiledningsøkter deltatt i per måned.                                  |
| Family_Income                   | Inntektsnivået til familien (Lav, Middels, Høy).                              |
| Teacher_Quality                 | Kvalitet på lærerne (Lav, Middels, Høy).                                      |
| School_Type                     | Type skole som eleven går på (Offentlig, Privat).                             |
| Peer_Influence                  | Innflytelse fra jevnaldrende på akademisk ytelse (Positiv, Nøytral, Negativ). |
| Physical_Activity               | Gjennomsnittlig antall timer med fysisk aktivitet per uke.                    |
| Learning_Disabilities           | Tilstedeværelse av lærevansker (Ja, Nei).                                     |
| Parental_Education_Level        | Høyeste utdanningsnivå til foreldrene (Videregående, Høgskole, Master).        |
| Distance_from_Home              | Avstand fra hjem til skole (Nær, Moderat, Lang).                              |
| Gender                          | Kjønn på studenten (Mann, Kvinne).                                            |
| Exam_Score                      | Endelig eksamensresultat.                                                     |


Datasettet finner dere her: **[StudentPerformanceFactors.csv](https://github.com/uit-bed-1304-h25/uit-bed-1304-h25.github.io/tree/main/data)**

In [2]:
import pandas as pd

df = pd.read_csv('./data/StudentPerformanceFactors.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

# Oppgave 1a
I cellen over er datarammen `df` lest inn, som inneholder samme datasett som vi så på i seminaret for **matplotlib**.

Visualiser distribusjonen av karakterer i datasettet ved hjelp av et historgram fra SeaBorn.

# Oppgave 1b
Bruk Seaborn til å lage det samme plottet som over, men nå skal du bare plottet de som har fått **karaktersum 80 eller høyere**.

# Oppgave 1c
Lag et boxplot som sammenligner fordelingen av karakterene for menn og kvinner.

### **Hva sier dette oss?**
Her ser vi at median-verdien er relativt lik, både for menn og kvinner, mens vi ser at det er flere *outliers* i bunnsjiktet blant menn.

Vi ser også at det er flere damer helt op toppen av karakterskalaen også.

# Oppgave 1d
Utforsk sammenhengen mellom studietid og karakterer. Her kan du bruke `sns.scatterplot()` funksjonen i SeaBorn. Så gjør det samme i matplotlib, og sammenlign.

# Oppgave 1e
Lag et "korrelasjonsvarmekart" (bedre kalt: **heatmap**) som viser hvordan ulike variabler i datasettet henger sammen.

I første om gang, se på følgende variabler: `Hours_Studied`, `Exam_Score`, `Sleep_Hours`, `Attendance`, `Previous_Scores` og `Physical_Activity` .

Hvilke informasjon får du ut av *heatmap'et*?

## **Oppgave 2**

I denne oppgaven skal dere bruke datasettet `bilparken_ssb.csv`, som dere finner i `/data` mappen på GitHub.

Til forskjell fra oppgave 1, går oppgave 2 ut på at **dere selv** skal utforske datasettet ved hjelp av Seaborn, Pandas og matplotlib. 

Likevel, her er noen føringer for oppgaven:
* Vis grunnleggende informasjon om datarammen `df_bil`.
* Sjekk for manglende verdier.
* Gjør flere ulike visualiseringer vha matplotlib og/eller SeaBorn.

In [24]:
import pandas as pd

df_bil = pd.read_csv('./data/bilparken_ssb.csv') 
df_bil

,Tid,Bilmerker,12 - 15 år,16 - 20 år,4 - 7 år,8 - 11 år,Over 20 år,Under 4 år,Gjennomsnittsalder ved vraking (år),Personbilbestand 31. desember,Personbiler vraket mot pant,Personbiler vraket mot pant (prosent av bestanden)
0,2021,Audi,30096,23230,27302,35723,12423,29778,19.2,158552.0,6390.0,4.0
1,2021,Bmw,33358,21524,33096,41841,13210,21429,18.7,164458.0,4104.0,2.5
2,2021,Bmw i,0,0,15935,207,0,9501,3.4,25643.0,41.0,0.2
3,2021,Chevrolet,1437,2666,449,1236,13639,64,21.9,19491.0,567.0,2.9
4,2021,Citroen,7839,4426,7424,11999,2218,5080,16.2,38986.0,2531.0,6.5
5,2021,Ford,38993,13186,27029,44904,18585,15657,17.2,158354.0,7148.0,4.5
6,2021,Honda,14955,11430,5903,8314,3923,1842,19.1,46367.0,2402.0,5.2
7,2021,Hyundai,10745,6745,14790,16483,1068,26874,16.1,76705.0,2023.0,2.6
8,2021,Kia,3908,1663,28986,16714,189,16877,13.8,68337.0,879.0,1.3
9,2021,Mazda,10196,3872,20317,16761,4720,8344,18.3,64210.0,2868.0,4.5
10,2021,Mercedes-Benz,26715,26360,35001,31742,24637,20225,20.6,164680.0,5716.0,3.5
11,2021,Mitsubishi,17101,8208,28384,24709,5556,12916,18.7,96874.0,3224.0,3.3
12,2021,Nissan,16193,10517,45345,37185,4963,21230,17.7,135433.0,3643.0,2.7
13,2021,Opel,15250,12854,13551,14075,11765,6808,18.7,74303.0,6950.0,9.4
14,2021,Peugeot,19911,11743,19744,24262,3249,16337,16.6,95246.0,5892.0,6.2
15,2021,Renault,2300,3499,12661,3821,1490,6976,17.0,30747.0,1878.0,6.1
16,2021,Skoda,19012,7025,31395,29179,1304,24215,15.7,112130.0,3002.0,2.7
17,2021,Subaru,8264,12078,10064,11322,3346,1941,18.9,47015.0,2140.0,4.6
18,2021,Suzuki,10567,14207,11272,10167,2682,7510,17.5,56405.0,2196.0,3.9
19,2021,Tesla,11,0,12452,41,0,47504,2.2,60008.0,55.0,0.1
20,2021,Tesla Motors,0,0,11383,5495,0,3,6.2,16881.0,74.0,0.4
21,2021,Toyota,70196,63080,65333,68520,30590,42712,18.6,340431.0,12332.0,3.6
22,2021,Volkswagen,70902,46672,97436,88517,29453,55692,18.1,388672.0,17380.0,4.5
23,2021,Volvo,40648,33993,44719,54829,30000,33331,19.9,237520.0,6238.0,2.6

# Din løsning under her: